name: jupyter-demo
channels:
- conda-forge
- defaults
dependencies:
- python=3.6.*
- numpy
- scipy
- scikit-learn
- keras
- tensorflow  # CPU-only version
- pandas
- matplotlib
- seaborn
- jupyter
- jupyterlab
- nb_conda
- ipywidgets
- jupyter_contrib_nbextensions
- beakerx
- bqplot
- invoke
- pip:
  - python-dotenv
