name: jupyter-demo
channels:
- conda-forge
dependencies:
- python=3.6.*
- numpy
- scipy
- scikit-learn
- keras
- tensorflow  # CPU-only version
- pandas
- dask
- matplotlib
- seaborn
- jupyter
- jupyterlab=0.31.*
- nb_conda
- ipywidgets
- jupyter_contrib_nbextensions
- beakerx
- bqplot
- invoke
- attrs
- pip:
  - python-dotenv
