name: jupyter-demo
channels:
  - conda-forge
packages:
  - python=3.6.*
  - numpy
  - scipy
  - scikit-learn
  - keras
  - tensorflow-cpu
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - nb_conda
  - ipywidgets
  - jupyter_contrib_nbextensions
  - beakerx
  - bqplot
  - nodejs
  - invoke
  - pip:
    - python-dotenv
